[build]
  publish = "dist"
  command = "npm run build"

# Handle dynamic routes properly
[[redirects]]
  from = "/reset-password/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/oauth-success"
  to = "/index.html"
  status = 200

# Catch-all for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 